# from ursina import *
# from ursina.shaders import lit_with_shadows_shader
# app = Ursina()
# ground = Entity(name="ground", model='cube', scale=(30,1,30), color=color.rgb(0.9294117647058824,0.7882352941176471,0.6862745098039216), texture='white_cube', texture_scale=(30,30), collider='box', shader=lit_with_shadows_shader)
# house1 = Entity(name="house1", model='assets/building_01.gltf', position=(-4,0.5,-4), collider='box', shader=lit_with_shadows_shader)
# house2 = Entity(name="house2", model='assets/building_01.gltf', position=(4,0.5,-4), collider='box', shader=lit_with_shadows_shader)
# house3 = Entity(name="house3", model='assets/building_01.gltf', position=(-4,0.5,4), collider='box', shader=lit_with_shadows_shader)
# house4 = Entity(name="house4", model='assets/building_01.gltf', position=(4,0.5,4), collider='box', shader=lit_with_shadows_shader)
# wall1 = Entity(name="wall1", model='cube', textures='white_cube', scale=(1,3.5,1), position=(1.5,2.25,1.5), color=color.rgb32(150,111,51), collider='box', shader=lit_with_shadows_shader)
# wall_n1 = Entity(name="wall_n1", model='assets/wall_03.gltf', position=(-10,0.5,15), collider='box', shader=lit_with_shadows_shader)
# wall_n2 = Entity(name="wall_n2", model='assets/wall_03.gltf', position=(0,0.5,15), collider='box', shader=lit_with_shadows_shader)
# wall_n3 = Entity(name="wall_n3", model='assets/wall_03.gltf', position=(10,0.5,15), collider='box', shader=lit_with_shadows_shader)
# wall_s1 = Entity(name="wall_s1", model='assets/wall_03.gltf', position=(-10,0.5,-15), collider='box', shader=lit_with_shadows_shader)
# wall_s2 = Entity(name="wall_s2", model='assets/wall_03.gltf', position=(0,0.5,-15), collider='box', shader=lit_with_shadows_shader)
# wall_s3 = Entity(name="wall_s3", model='assets/wall_03.gltf', position=(10,0.5,-15), collider='box', shader=lit_with_shadows_shader)
# wall_w1 = Entity(name="wall_w1", model='assets/wall_03.gltf', position=(-15,0.5,-10), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# wall_w2 = Entity(name="wall_w2", model='assets/wall_03.gltf', position=(-15,0.5,0), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# wall_w3 = Entity(name="wall_w3", model='assets/wall_03.gltf', position=(-15,0.5,10), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# wall_e1 = Entity(name="wall_e1", model='assets/wall_03.gltf', position=(15,0.5,-10), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# wall_e2 = Entity(name="wall_e2", model='assets/wall_03.gltf', position=(15,0.5,0), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# wall_e3 = Entity(name="wall_e3", model='assets/wall_03.gltf', position=(15,0.5,10), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# wall2 = Entity(name="wall2", model='cube', textures='white_cube', scale=(1,5,1), position=(15,3,15), color=color.rgb32(150,111,51), collider='box', shader=lit_with_shadows_shader)
# north_fw1 = Entity(name="north_fw1", model='assets/wall_01.gltf', position=(-6,0.5,10), collider='box', shader=lit_with_shadows_shader)
# north_fw2 = Entity(name="north_fw2", model='assets/wall_01.gltf', position=(0,0.5,11), collider='box', shader=lit_with_shadows_shader)
# north_fw3 = Entity(name="north_fw3", model='assets/wall_01.gltf', position=(6,0.5,10), collider='box', shader=lit_with_shadows_shader)
# south_fw1 = Entity(name="south_fw1", model='assets/wall_01.gltf', position=(-6,0.5,-10), collider='box', shader=lit_with_shadows_shader)
# south_fw2 = Entity(name="south_fw2", model='assets/wall_01.gltf', position=(0,0.5,-11), collider='box', shader=lit_with_shadows_shader)
# south_fw3 = Entity(name="south_fw3", model='assets/wall_01.gltf', position=(6,0.5,-10), collider='box', shader=lit_with_shadows_shader)
# west_fw1 = Entity(name="west_fw1", model='assets/wall_01.gltf', position=(-10,0.5,-6), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# west_fw2 = Entity(name="west_fw2", model='assets/wall_01.gltf', position=(-11,0.5,0), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# west_fw3 = Entity(name="west_fw3", model='assets/wall_01.gltf', position=(-10,0.5,6), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# east_fw1 = Entity(name="east_fw1", model='assets/wall_01.gltf', position=(10,0.5,-6), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# east_fw2 = Entity(name="east_fw2", model='assets/wall_01.gltf', position=(11,0.5,0), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# east_fw3 = Entity(name="east_fw3", model='assets/wall_01.gltf', position=(10,0.5,6), rotation=(0,90,0), collider='box', shader=lit_with_shadows_shader)
# wall3 = Entity(name="wall3", model='cube', textures='white_cube', scale=(1,2.5,1), position=(9.5,1.75,8), color=color.rgb32(150,111,51), collider='box', shader=lit_with_shadows_shader)
# small_wall = Entity(name="small_wall", model='assets/wall_02.gltf', position=(-9,0.5,0), collider='box', shader=lit_with_shadows_shader)
# wall6 = Entity(name="wall6", model='cube', textures='white_cube', scale=(1,2,1), position=(-9,1.5,1), color=color.rgb32(150,111,51), collider='box', shader=lit_with_shadows_shader)
# pillar1 = Entity(name="pillar1", model='assets/Pillar.gltf', position=(0,0.5,0), collider='box', shader=lit_with_shadows_shader)
# wall4 = Entity(name="wall4", model='cube', textures='white_cube', scale=(1,5.25,1), position=(-0.5,3.1,-0.5), color=color.rgb32(150,111,51), collider='box', shader=lit_with_shadows_shader)
# crate = Entity(name="crate", model='assets/Box_01.gltf', scale=(1,1,1), position=(10,1,0), collider='box', shader=lit_with_shadows_shader)
# wall5 = Entity(name="wall5", model='cube', textures='white_cube', scale=(1,1,1), position=(10,1,-1), color=color.rgb32(150,111,51), collider='box', shader=lit_with_shadows_shader)
# sun = DirectionalLight(shadows=True, rotation=(45,-45,45))
# EditorCamera()
# app.run()

from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController

app = Ursina()

col = Entity(model='assets/collider.obj', scale=0.5, collider='mesh', position=(0,0,0), visible=False)
mes = Entity(model='assets/map.obj', scale=0.5, collider=col, position=(0,0,0), visible=True)
wall1 = Entity(model='quad', texture='sky_sunset', texture_scale=(10,1), scale=(100,10,1), collider='box', position=(-6,5,15), visible=True)
wall2 = Entity(model='quad', texture='sky_sunset', texture_scale=(10,1), scale=(100,10,1), collider='box', position=(-6,5,-20), rotation=(0,-180,0), visible=True)
wall3 = Entity(model='quad', texture='sky_sunset', texture_scale=(1,1), scale=(35,10,1), collider='box', position=(44,5,-2.5), rotation=(0,90,0), visible=True)
wall4 = Entity(model='quad', texture='sky_sunset', texture_scale=(1,1), scale=(35,10,1), collider='box', position=(-56,5,-2.5), rotation=(0,-90,0), visible=True)

# EditorCamera()
FirstPersonController(y=50, speed=5)

Sky()

app.run()